# Generated by Django 4.2.4 on 2023-11-02 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoTrabajadores', '0003_delete_authgroup_delete_authgrouppermissions_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trabajadores',
            options={'managed': True},
        ),
    ]
