# Generated by Django 4.2.4 on 2023-11-07 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoTrabajadores', '0004_alter_trabajadores_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trabajadores',
            options={'managed': False},
        ),
    ]
